### ISSUE TITLE
Permission to Stellarium/stellarium.github.io.git denied

### ISSUE THREAD

**Issue by steelrooter** [Stellarium/stellarium.github.io#1]
I was trying to push a fix, but the access to git repo is denied. Is this a mistake or are we not supposed to contribute to this repo?

**Comment by xalioth** [comment]
Well, you should make a pull request rather than directly push to the git.
We'll review it and merge it if everything is fine!

**Comment by steelrooter** [comment]
Sorry, wasn't aware of the concept of forking. Got it. Closing this issue.
