### ISSUE TITLE
Canary Islands landscapes should be listed below Africa not Europe

### ISSUE THREAD

**Issue by amlopezalonso** [Stellarium/stellarium.github.io#10]
At present, only one out of three existing Canarian landscapes in landscape repository is correctly listed below Africa section being the other two (Las Cañadas & Roque de los Muchachos) listed as Europe. If I'm not wrong landscapes classification is based as one could expect on continent location not political membership. Hence even when the Canary Islands belong to the EU they are undoubtedly African in terms of geographical (and thus astronomical) location.

Kind regards,
Antonio

**Comment by gzotti** [comment]
Difficult question. I would have asked a Canarian whether he feels "African" or "European".

**Comment by amlopezalonso** [comment]
Well I'm Canarian, but whatever I feel, either "African" or "European" is irrelevant because as I said it is not about political / cultural matters. It's about whether landscape classification is geographical or not. And given astronomy observations depends on geographical coordinates you will agree that putting Canary Islands under Europe is misleading at least.
