### ISSUE TITLE
Should deprecate older websites

### ISSUE THREAD

**Issue by jipodine** [Stellarium/stellarium.github.io#13]
### Expected Behaviour
If old websites are to be kept, they should be marked deprecated: Sourceforge, Launchpad. I tried to find a way to correct a small typo in a translation, and I almost gave up, after following old documentation.

### Actual Behaviour
Mark old website as deprecated.

### System
Any.

**Comment by gzotti** [comment]
Sourceforge says in a bright blue button "This project can now be found here". Q&A are still useful.
The Launchpad could be further switched down, indeed, and a note added to the welcome text.

**Comment by alex-w** [comment]
Launchpad has old Q&A section which still useful + we use PPA at launchpad.net for prepare deb packages for Ubuntu.

**Comment by jipodine** [comment]
I understand that there is information that was not transferred. However it is surrounded by outdated stuff. About Sourceforge, neither the website nor the wiki are updated:

http://stellarium.sourceforge.net/
http://stellarium.sourceforge.net/wiki/index.php/Main_Page

For example, I read the FAQ, then went to the wiki. It tells you that if you want to contribute to translation, you should register to launchpad. But on launchpad, the message is confusing: 

>  Stellarium does not use Launchpad to translate its messages.

You can also download old version of software and documentation on Sourceforge... 

Without updating the old resources, at least a warning in a header (for every page) would be nice, with a manual redirection.

And yes, I saw the up-to-date packages on Launchpad, which is confusing also, because the it means that there is activity.

**Comment by alex-w** [comment]
> I tried to find a way to correct a small typo in a translation, and I almost gave up, after following old documentation.

Are you tried start translation from stellarium.org website?

**Comment by jipodine** [comment]
> Are you tried start translation from stellarium.org website?
I eventually found it. And the resource is great. I will use it, now.

My problem was related to the old <https://stellarium.sourceforge.net/> website that is misleading. It could confuse others.
