### ISSUE TITLE
https

### ISSUE THREAD

**Issue by DarthGandalf** [Stellarium/stellarium.github.io#14]
Why http://stellarium.org doesn't redirect to https://stellarium.org ? Both these links work

**Comment by alex-w** [comment]
Old versions of Stellarium still want to use HTTP protocol

**Comment by DarthGandalf** [comment]
I see. How long are old versions supported? Which version is that?

**Comment by alex-w** [comment]
The issue was find and fixed in series 0.18 - at least debian stable has v0.18.3 in main repository. Probably CentOS has a similar version in the currently supported releases too.

I’ve enabled redirect to HTTPS and I hope we’ll not receive bug reports...

**Comment by DarthGandalf** [comment]
Thanks!

**Comment by DarthGandalf** [comment]
https://repology.org/project/stellarium/versions doesn't list CentOS at all, it lists EPEL though with 0.12 for EPEL 7 and 0.20 for EPEL 8
