### ISSUE TITLE
Stellarium-github-io two phrases not working

### ISSUE THREAD

**Issue by ilkant** [Stellarium/stellarium.github.io#36]
### Expected Behaviour
On http://stellarium.org/ site there are screenshots page. And there are text Please select an image. When finnish language is chosen, it should be Ole hyvä ja valitse kuva. There are also text Donate to our collective. It should be Lahjoita yhteisöllemme.

### Actual Behaviour
In screenshots page there are text Please select an image. Text is english even finnish language is selected. And the text is translated in Transifex.

Donate to our collective text is not in Transifex. So, it shoude be there.

Also the captions of big pictures are english. They should be in Transifex too, so translators could be able to translate them.

### Steps to reproduce
1. In main page choose view screenshots
2. Look the area where big picture comes. There is text Please select an image. And bottom of page there are Donate to our collective.
 
### System
* Operating system: <Kubuntu 22.10>

### Logfile
Not useful with this bug.

**Comment by alex-w** [comment]
Both are images and we cannot translate them on-the-fly
