### ISSUE TITLE
Donate link leads to a PayPal page that is in French and there are not other language options

### ISSUE THREAD

**Issue by brianpeiris** [Stellarium/stellarium.github.io#5]
The donate button at the bottom of the page points to https://sourceforge.net/p/stellarium/donate/ which leads to a french paypal page. Ideally it should be in the user's local language, or at least in English.

![image](https://user-images.githubusercontent.com/79419/43054059-a800332c-8de4-11e8-99d1-7b6d8a3e7709.png)

**Comment by xalioth** [comment]
I think we should just get rid of this link altogether..
