### ISSUE TITLE
Recover old Sourcforge Wiki page 

### ISSUE THREAD

**Issue by JonSeamans** [Stellarium/stellarium.github.io#51]
If possible, I'd like to recover a wiki page that shows how to use JPL Horizons osculating elements specifically for spacecraft.
The original location was "http://stellarium.sourceforge.net/wiki/index.php/JPL_HORIZONS" which is no longer accessible.  It appears that the Stellarium Wiki library is transitioning to Github.

I'm pretty new to Github and its user interface.  Is this Wiki page available, and if so, how do I access it?

Thank you!
Jon

**Comment by alex-w** [comment]
Old page you can found [here](https://web.archive.org/web/20171116125446/http://stellarium.org/wiki/index.php/JPL_HORIZONS), but this page is really too old - we changed the some variables for orbital elements in `ssystem_minor.ini` file (please the Stellarium User Guide and ssystem files for details), plus JPL horisons service changed unit of measurement for some variables. Probably old online service to convert JPL HORIZONS ephemerides into Stellarium format is not working anymore too.

@gzotti maybe adding some short introduction for conversion JPL HORIZONS data into Stellarium format into SUG will be good idea?

**Comment by gzotti** [comment]
Sure. Just that this page (2007?) predates my activity here, and I think this is the fist time I am reading this. I am also no regular user of Horizons. I can add a page, but please expect errors and report corrections.

**Comment by alex-w** [comment]
I have a some experience for using Horizons with Stellarium and I can write a withdraw in next couple days

**Comment by gzotti** [comment]
Actually most of the caveats are meanwhile solved. It just requires reading the table of symbols delivered by JPL.

**Comment by gzotti** [comment]
Added in https://github.com/Stellarium/stellarium/commit/47ba336f227d35281db21a44e09ace18df45a1e4
